{{- if and (eq .Values.certificate.selfSigned false) (eq .Values.certificate.certManager false) }}

apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: "2023-01-02T00:06:54Z"
  generation: 1
  name: opa-sidecar-admission-controller-minikube-webhook
  resourceVersion: "118453"
  uid: 3c0333ca-740f-475f-8b6c-f9dea3e2ea09
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUdWVENDQkQyZ0F3SUJBZ0lDQStrd0RRWUpLb1pJaHZjTkFRRUxCUUF3Z1oweEREQUtCZ05WQkFZVEExVlQKUVRFUk1BOEdBMVVFQ0JNSVNXeHNhVzV2YVhNeEVEQU9CZ05WQkFjVEIwTm9hV05oWjI4eEZqQVVCZ05WQkFrVApEVk4wY21WbGRFRmtaSEpsYzNNeERqQU1CZ05WQkJFVEJUWXdOakF4TVEwd0N3WURWUVFLRXdSVFpXeG1NUkV3CkR3WURWUVFMRXdoVFpXeG1WVzVwZERFZU1Cd0dBMVVFQXhNVlUyVnNabE5wWjI1bFpFTmxjblJwWm1sallYUmwKTUI0WERUSXpNREV3TWpBd01EWTBOMW9YRFRJMk1ERXdNakF3TURZME4xb3dnWjB4RERBS0JnTlZCQVlUQTFWVApRVEVSTUE4R0ExVUVDQk1JU1d4c2FXNXZhWE14RURBT0JnTlZCQWNUQjBOb2FXTmhaMjh4RmpBVUJnTlZCQWtUCkRWTjBjbVZsZEVGa1pISmxjM014RGpBTUJnTlZCQkVUQlRZd05qQXhNUTB3Q3dZRFZRUUtFd1JUWld4bU1SRXcKRHdZRFZRUUxFd2hUWld4bVZXNXBkREVlTUJ3R0ExVUVBeE1WVTJWc1psTnBaMjVsWkVObGNuUnBabWxqWVhSbApNSUlDSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQWc4QU1JSUNDZ0tDQWdFQXpJZEt5QzNMY3p5MlRIV3phdCtBCmJPRXJRQkUzR1RwSmtYWDJ6RTA4TU1SSXN3dzhwOGd1SHdJQnJrWExxUmEwS1h2QVhMV1RoclZrNVJuenpYcHYKZjNHcXBsajJjdkx4SVVjUDFPMDdsbmtDb1JiTGRhaUJ1SDI5YUU2b055WHlIVUdTZHlTRGdQbW14NW5lM3ppdgpoVG00a2FkRWtESzBvSXFRcTc5eW55SDJhY2FhQlo4ampCUUUzREhTRWpZOUkyVkhlaEVCMndTWjZBenFEVVVOCnhoZUFRTDJGc2tOQngvWiszb2tqT0NGSkVLQjdnUDZFZ0Mrc0E2Y3hoNXVqZkFoSjdsZzNsRW1ETTlNcWU1OEcKOG5DWEpwUnBSbXZvd1N1em9ueVVLSU1aWlZGTDJpVGxQeEN6WlZvNDBYMXhTVEdVODB0VkhzTEdjdlhMV3cvVwpGaTZSN3NqTlFqKzVjMlpMaUU2YytMaENaMDBYTkx5Wm43Q3VGbFc0NTB2b3Vrem9BMVdDR3ROL01Cck10cWRyCkpPL25yaS81RnZQbGxOQTltazFhM2lwVVBwL1ZZNFhGSHVwSFZUNnFOeGI5TEJCejMrQmg3WnM5ZlRNT0pYSW8KV2JJYWk0dUxPV1VaQmwzSUZBblR0QjVaeVFYMjJOQVFoZWV6Rkt4a01VYUl1TVVzTzVBNXRVcGtNdWZWeGEvagpJbHRESEVBbWVnc1lWM2xlYmk4b0xoL0xDYkpzckhVS1NnZGdhUE9Cd283WHhlYmszUGxxbWtLbjdkYVBDVEIwCkRoUHRVYkRsZTJXZTMxU3NzbStVZmVUYy9WTk5Vcm5yZHJvSlRVcTNwcWplcncvUG5VL0g0NjFrUmloV0tFRjMKNFk3Y015a2JVK3ZxOVlDQXVxTDRvME1DQXdFQUFhT0JuRENCbVRBT0JnTlZIUThCQWY4RUJBTUNCNEF3SFFZRApWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3SUdDQ3NHQVFVRkJ3TUJNR2dHQTFVZEVRUmhNRitDRlZObGJHWlRhV2R1ClpXUkRaWEowYVdacFkyRjBaWUpHYjNCaExYTnBaR1ZqWVhJdFlXUnRhWE56YVc5dUxXTnZiblJ5YjJ4c1pYSXQKYldsdWFXdDFZbVV1YjNCaExYTjVjM1JsYlM1emRtTXVZMngxYzNSbGNpNXNiMk5oYkRBTkJna3Foa2lHOXcwQgpBUXNGQUFPQ0FnRUFOdVFNaW9WOUR2clNYVzJ2eEJGVm9ucXlCZk45UzhrYks2NXUzTWRDM0dtdG12a1ZHQncrClFKVXBRT0ZLZ1oyWkJ0NzYwNUhDbW1yeDg2Ny8rZ21yNjA4TURnR1J3MjBpak5OaURLaExja3FERWVjaVBlNkwKTFVTK28yekdtMU8yeFBjTVg3QXRDU0NGL2p1L0RQbFlYMWxZZG5nbEhnU2NsdFNnMXJIejVUU1Jmc2FNenk1NQpxbE1ha1hVZm9mSGkxeGVCeTVLbkN6ajNrVjVsWC90TWQ1N3B4ZEplbGxtWDRhcENDY1FGbk93alljR3RlYTZiCjZIenBaMXExc1pWWm5ydUNmQXRCNkp6alBDYjJ0NEFIQXB5L1VLcnB4YnZQaDdUSno1NkVMTlJmVU1za0NSbDQKUGhFNE5sU0NqVEkxd3pvT3puR0hyeHkybUwrcGpzd1dja3FqYWJUcDNKb1VCUjJzcnducUd6S21JVnRYUUd6TApwZHBSSFlwcXFhZi9ERHY4QVB0SjArUEM0Si9TdFd5OGhoYUpuUG5sOWowL084bm52SmlXSXl1Uk81MzVTdGhBCjE3OEc5cldhWmI3VnM0c2tJOU5uWW43S3hyUGZXNnM5QnVhdXhsQnhoWno5MEh1dEcxOFJES1p4Qy8rTEk0M0QKdkhrQ3Jsem1Gc251NmVzcVdZbGhuVDZwdWlLbDJyZUZNVE03VDBaWFJEWll5S0g0R3YwYkgzQkUrWGRvTHZtZQpjMlZEUi9vV2dNbkJScHpyNXFSTitRcVVRRlV4eDVqM3o0ZnhGbkMzc3pwdDNWaEpKYUZlekNaR1lGYk9jb1dTCng2YlBCcEwrejRHa0s0VTlqMEhBa0hiVEYrM1grdk9GSk9EQlpGeWpabmk5d09IbWJqNVhmaUk9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: opa-sidecar-admission-controller-minikube
      namespace: opa-system
      path: /v0/data/istio/inject
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: opa-sidecar-admission-controller-minikube-webhook.twdps.io
  namespaceSelector:
    matchLabels:
      opa-injection: enabled
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    scope: '*'
{{- end }}