name: lint, test, and release charts

on:
  push:
    branches:
      - main

jobs:
  release-charts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.10.3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1

      - name: Lint charts
        run: ct lint --chart-dirs charts --check-version-increment --exclude-deprecated --all

      - name: Create kind cluster
        uses: helm/kind-action@v1.5.0

      - name: Run chart-testing (install)
        run: ct install --chart-dirs charts --exclude-deprecated --all

      # would like to substitute a custom, terragrunt based helm chart install integration tests
      # but misunderstanding something about running bash scripts in a github action
      # even a simple echo message script will fail so there must be a trick to running bash
      # - name: run tests against changed charts
      #   run: ./tests/test-changes.sh

      - name: set github user information
        run: |
          git config --global user.email "twdps.io@gmail.com"
          git config --global user.name "twdpsio"
          
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"